name: Playwright Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  playwright-docker:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        browser-name: [ "chrome", "firefox", "safari" ]
        python-version: [ "3.8", "3.12" ]

    container:
      image: mcr.microsoft.com/playwright/python:v1.41.0-jammy
      options: --ipc=host

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup tests
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0
          
      - name: Extract tox env
        run: |
          tox_env_variable=$(echo "${{ matrix.python-version }}" | sed 's/\.//g')
          echo "TOX_ENV=${tox_env_variable}" >> $GITHUB_ENV
      
      # Needed for Firefox
      - name: Set HOME to /root
        run: |
          echo "HOME=/root" >> $GITHUB_ENV  # Set HOME environment variable

      - name: Run Playwright ${{ matrix.browser-name }} tests with py${{ matrix.python-version }}
        run: |
          tox -e py${{ env.TOX_ENV }}-playwright-${{ matrix.browser-name }} -- --headless -v --sv
