name: Selenium Selenoid Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  selenium-selenoid:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        image: [ "selenoid/chrome:128.0", "selenoid/firefox:125.0"]
        python-version: [ "3.8", "3.12" ]

    services:
      selenoid:
        image: ${{ matrix.image }}
        options: --privileged --memory=4g
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Setup tests
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0
      
      - name: Extract tox env
        run: |
          tox_env_variable=$(echo "${{ matrix.python-version }}" | sed 's/\.//g')
          echo "TOX_ENV=${tox_env_variable}" >> $GITHUB_ENV

      - name: Extract Browser Name
        run: |
          browser_name=$(echo "${{ matrix.image }}" | sed -E 's|.*/([^:]+):.*|\1|')
          echo "BROWSER=${browser_name}" >> $GITHUB_ENV

      - name: Run Selenium ${{ env.BROWSER }} tests with py${{ matrix.python-version }}
        run: |
          tox -e py${{ env.TOX_ENV }}-selenium-${{ env.BROWSER }} -- --env remote --headless -v
